### ISSUE TITLE
0.6.0b2 Not loading in Arch Linux

### ISSUE THREAD

**Issue by zeronoises** [bongozone/bongozone.github.io#1]
Log reads;
``Failed to load library /home/zero/.Rack/plugins/PulsumQuadratum/plugin.so: /usr/lib/libm.so.6: version GLIBC_2.27' not found (required by /home/zero/.Rack/plugins/PulsumQuadratum/plugin.so)`

**Comment by wizardishungry** [comment]
Relates to VCVRack/Rack#873 (should have a working beta monday)
